/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void simpleAdditionTest(){
      MathOne math1 = new MathOne();
      assertEquals(math1.simpleAddition(1,1), 2);
    }

    @Test
    void simpleMultiplicationTest(){
      MathTwo math2 = new MathTwo();
      assertEquals(math2.simpleMultiplication(1,1), 1);
    }

    @Test
    void simpleIntegrationTest(){
      App app = new App();
      assertEquals(app.squareSum(2,3), 25);
    }
}
